[ControlCenter]
diskUsagePath=/
iconMode=nerd
powerCommand=wlogout
settingsCommand=systemsettings

[Mpris]
alwaysVisible=false

[SystemTray]
debugDetails=false

[Weather]
latitude=40.7128
longitude=-74.006
refreshMinutes=5
temperatureUnit=celsius

[Window]
barHeight=52
barLayerSpacing=5
barLayerSpacingBottom=0
barLayerSpacingLeft=9
barLayerSpacingRight=9
barLayerSpacingTop=5
