[ControlCenter]
diskUsagePath=/
iconMode=nerd
powerCommand=wlogout

[Mpris]
alwaysVisible=false

[Weather]
latitude=40.7128
longitude=-74.006
refreshMinutes=20
temperatureUnit=celsius

[Window]
barHeight=52
barLayerSpacing=5
barWidth=2000

[SystemTray]
debugDetails=false
