[ColorScheme]
lighColors=CatppuccinLatteNitrux
darkColors=CatppuccinMochaNitrux

[ControlCenter]
diskUsagePath=/home
iconMode=system16
powerCommand=wlogout
settingsCommand=maui-settings

[Debug]
debugDetails=false
simulateBatteryAvailable=false
simulateBatteryCharging=false
simulateBatteryOnAcPower=false
simulateBatteryPercentage=72
simulateBrightnessAvailable=false
simulateBrightnessPercentage=65

[Mpris]
alwaysVisible=false

[SystemTray]
debugDetails=false

[Weather]
latitude=40.7128
longitude=-74.006
refreshMinutes=5
temperatureUnit=celsius

[Window]
barHeight=52
barLayerSpacingBottom=0
barLayerSpacingLeft=9
barLayerSpacingRight=9
barLayerSpacingTop=5
screenPlacement=all
