[Appearance]
height=66
iconMode=system
width=292

[Behavior]
hideAnimationDuration=200
hideTimeout=2000
showAnimationDuration=200

[Controls]
brightnessStep=10
volumeStep=5

[Position]
bottomOffset=114
