[Appearance]
iconMode=system
width=292
height=66

[Position]
bottomOffset=114

[Behavior]
hideTimeout=2000
showAnimationDuration=200
hideAnimationDuration=200

[Controls]
volumeStep=5
brightnessStep=10
