# Desklock defaults

[Appearance]
BackgroundImage=/usr/share/wallpapers/Aqua/contents/images/2560x1440.png
BackgroundBlurRadius=64
BackgroundOverlayOpacity=0.76
# Supports %u for the current username and %h for the current home directory.
AvatarImage=~/.face

[Clock]
TimeFormat=hh:mm
DateFormat=dddd, dd MMMM yyyy
LowercaseDate=false

[Battery]
Enabled=true
UpdateInterval=30000

[Media]
Enabled=true

[SystemMonitor]
Enabled=true
UpdateInterval=3000

[Behavior]
HideCursor=true
FadeInDuration=350
FadeOutDuration=250
