[Appearance]
AvatarImage=~/.face
BackgroundBlurRadius=64
BackgroundImage=/usr/share/wallpapers/Aqua/contents/images/2560x1440.png
BackgroundOverlayOpacity=0.76

[Battery]
Enabled=true
UpdateInterval=30000

[Behavior]
FadeAnimationsEnabled=true
FadeInDuration=350
FadeOutDuration=250
GracePeriod=0
HideCursor=false
IdleLockTimeout=300

[Clock]
DateFormat=
LowercaseDate=false
TimeFormat=hh:mm

[Media]
Enabled=true

[SystemMonitor]
Enabled=true
UpdateInterval=3000
