[Appearance]
edgeMargin=5
iconSize=40

[Behavior]
autoHide=false
autoHideDelay=500
launcherShortcutsEnabled=false
launcherHoldDelay=2300
launcherModeDuration=995

[Launchers]
pinned=org.kde.fiery, org.kde.station, org.kde.index, org.kde.nota, org.kde.vvave, org.kde.pix, org.nitrux.appfinder

[Window]
height=0
screenPlacement=all
showAboveFullscreen=false
width=0
