[Appearance]
edgeMargin=5
iconSize=40

[Behavior]
autoHide=false
autoHideDelay=500

[Launchers]
pinned=org.kde.fiery, org.kde.station, org.kde.index, org.kde.nota, org.kde.vvave, org.kde.pix
[Window]
height=0
screenPlacement=all
showAboveFullscreen=false
width=0
