#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Add OhMyZSH.

git clone https://github.com/ohmyzsh/ohmyzsh.git /etc/skel/.oh-my-zsh


# -- Add p10k for OhMyZSH.

mkdir -p /etc/skel/.oh-my-zsh/custom/themes/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /etc/skel/.oh-my-zsh/custom/themes/powerlevel10k


# -- Add xdg_dir environment variables.

{ 
  echo 'XDG_CONFIG_DIRS=/etc/xdg'
  echo 'XDG_DATA_DIRS=/usr/local/share:/usr/share'
  echo 'MOZ_USE_XINPUT2=1'
  echo 'MOZ_ENABLE_WAYLAND=1'
} >> /etc/environment


# -- Add /Applications to sudoers.

sed -i "s|secure_path\=.*$|secure_path=\"$PATH:/Applications\"|g" /etc/sudoers
sed -i "/env_reset/d" /etc/sudoers


# -- Use ZSH in userland.

sed -i 's+SHELL=/bin/sh+SHELL=/bin/zsh+g' /etc/default/useradd
sed -i 's+DSHELL=/bin/bash+DSHELL=/bin/zsh+g' /etc/adduser.conf


# 1. Register the Nitrux cursor as a high-priority alternative
# Syntax: install <link> <name> <path> <priority>
update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/nitrux_snow_cursors/index.theme 90

# 2. Force set it as the selection
update-alternatives --set x-cursor-theme /usr/share/icons/nitrux_snow_cursors/index.theme


#	-- Overwrite file from bash.

cp -rf /etc/skel/.bak.bashrc /etc/skel/.bashrc
