[General]
height=600
width=600
x=0
y=0

[Browser]
adBlockEnabled=true
adblockDetectionBlockerEnabled=false
allowCamera=false
allowDesktopCapture=false
allowGeolocation=false
allowMicrophone=false
allowMouseLock=false
allowNotifications=false
autoLoadIconsForPage=true
autoLoadImages=true
autoSave=false
backgroundColor=@Variant(\0\0\0\x43\x1\xff\xff\x18\x18\x18\x18%%\0\0)
blockThirdPartyCookies=false
cookieBannerBlocker=false
customUserAgent=
dnsPrefetchEnabled=false
doNotTrack=true
dohEnabled=false
dohUrl=https://cloudflare-dns.com/dns-query
downloadsPath=~/
errorPageEnabled=true
forceDarkMode=false
fullScreenSupportEnabled=true
homePage=@Variant(\0\0\0\x11\0\0\0\x16https://duckduckgo.com)
httpsOnly=false
javascriptCanAccessClipboard=false
javascriptCanOpenWindows=true
javascriptEnabled=true
localStorageEnabled=true
pdfViewerEnabled=true
playbackRequiresUserGesture=true
restoreSession=true
screenCaptureEnabled=true
searchEnginePage="@Variant(\0\0\0\x11\0\0\0\x1ahttps://duckduckgo.com/?q=)"
sessionUrlsJson=
showScrollBars=true
subscribeBlockerEnabled=false
switchToTab=false
tabSleepDelay=15
tabSleepEnabled=true
thirdPartyCookiesWhitelistJson=[]
webGLEnabled=true
webRTCPublicInterfacesOnly=true
widevineEnabled=false
zoomFactor=1
