[General]
height=648
width=1263
x=0
y=0

[Browser]
adBlockEnabled=true
adblockDetectionBlockerEnabled=true
allowCamera=false
allowDesktopCapture=false
allowGeolocation=false
allowMicrophone=false
allowMouseLock=false
allowNotifications=false
autoLoadIconsForPage=true
autoLoadImages=true
autoSave=false
backgroundColor=@Variant(\0\0\0\x43\x1\xff\xff\x18\x18\x18\x18%%\0\0)
blockAmpLinks=true
blockThirdPartyCookies=false
cookieBannerBlocker=true
customUserAgent=
dnsPrefetchEnabled=true
doNotTrack=true
dohEnabled=true
dohUrl=https://cloudflare-dns.com/dns-query
downloadsPath=/home/uri/Descargas
errorPageEnabled=true
forceDarkMode=false
fullScreenSupportEnabled=false
globalPrivacyControl=true
homePage=@Variant(\0\0\0\x11\0\0\0\x16https://duckduckgo.com)
httpsOnly=true
javascriptCanAccessClipboard=false
javascriptCanOpenWindows=true
javascriptEnabled=true
localStorageEnabled=true
pdfViewerEnabled=true
playbackRequiresUserGesture=true
restoreSession=true
screenCaptureEnabled=true
searchEnginePage="@Variant(\0\0\0\x11\0\0\0\x1ahttps://duckduckgo.com/?q=)"
sessionUrlsJson=""
showScrollBars=true
stripTrackingParams=true
subscribeBlockerEnabled=true
switchToTab=false
tabSleepDelay=30
tabSleepEnabled=false
thirdPartyCookiesWhitelistJson=[]
webGLEnabled=true
webRTCPublicInterfacesOnly=true
widevineEnabled=false
zoomFactor=1

[Downloads]
entriesJson=[]
