[General]
height=799
width=1090
x=0
y=0

[Browser]
autoPlayPreviews=true
dirConf=true
floatyUI=true
gridSize=3
lastSession=
lastTabIndex=0
lastUsedTag=
listSize=0
overviewStart=false
previewFiles=false
previewerWindow=true
quickSidebarSection=true
restoreSession=false
showActionsBar=true
showHiddenFiles=true
showThumbnails=true
sideBarWidth=180
sidebarSections=13, 1, 3, 2
syncTerminal=true
terminalColorScheme=catppuccin-mocha
terminalExecutable=/usr/bin/station
terminalFollowsColorScheme=false
viewType=1
windowTranslucency=true

[Sorting]
foldersFirst=true
group=false
sortBy=11
sortOrder=0
