[General]
height=648
width=1263
x=0
y=0

[Browser]
autoPlayPreviews=true
dirConf=true
floatyUI=true
gridSize=3
lastSession=
lastTabIndex=0
lastUsedTag=
listSize=0
overviewStart=false
previewFiles=false
previewerWindow=true
quickSidebarSection=true
restoreSession=false
showActionsBar=true
showHiddenFiles=false
showThumbnails=true
sideBarWidth=180
sidebarSections=13, 1, 3, 2
syncTerminal=true
terminalColorScheme=catppuccin-mocha
terminalExecutable=/usr/bin/station
terminalFont=@Variant(\0\0\0@\0\0\0\x16\0M\0\x65\0s\0l\0o\0L\0G\0S\0 \0N\0\x46@$\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
viewType=1
windowTranslucency=true

[Sorting]
foldersFirst=true
group=false
sortBy=11
sortOrder=0
