[General]
enableOCR=true
height=648
ocrBlockType=0
ocrConfidenceThreshold=40
ocrPreprocessing=false
ocrSegMode=0
ocrSelectionType=0
previewBarVisible=false
slideshowInterval=5
slideshowLoop=true
tagBarVisible=true
width=1263
x=0
y=0

[Browser]
autoReload=true
fitPreviews=false
gpsTags=false
lastUsedTag=
previewSizePreset=medium
showLabels=false
sortBy=modified
sortOrder=1
