[General]
adaptiveColorScheme=false
alertProcess=false
antialiasText=true
blinkingCursor=true
colorScheme=catppuccin-mocha
colorStyle=1
enableBold=true
enableSideBar=true
font=@Variant(\0\0\0@\0\0\0\x16\0\x43\0\x61\0m\0i\0n\0g\0o\0\x43\0o\0\x64\0\x65@$\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
fullCursorHeight=true
height=648
historySize=-1
keysModelCurrentIndex=0
lastSession=@Variant(\0\0\0\t\0\0\0\x1\0\0\0\t\0\0\0\x1\0\0\0\b\0\0\0\x1\0\0\0\b\0p\0\x61\0t\0h\0\0\0\n\0\0\0\x12\0/\0h\0o\0m\0\x65\0/\0u\0r\0i)
lastTabIndex=0
lineSpacing=0
preventClosing=true
restoreSession=false
showSignalBar=false
tabTitleStyle=2
watchForSilence=false
width=814
windowOpacity=0.8
windowTranslucency=false
x=0
y=0
