[General]
height=648
width=814
x=0
y=0

[Output]
current_plugin=pipewire

[OutputPipeWire]
left_volume=100
right_volume=100

[PulseAudio]
left_volume=100
right_volume=100

[SETTINGS]
SOURCES=

[Settings]
closeAfterSleep=false
fetchArtwork=true
focusViewDefault=false
preferredOutput=pipewire
preferredOutputUserSet=true
showTitles=true
sleepOption=none
volume=100

[Volume]
left=100
right=100
